Week 4 Homework
==============
## 书面作业
### 6.2
研究同一地区土壤所含可给态磷的情况, 得到18组数据如表6.18所示. 表中$X_1$为土壤中所含无机磷, $X_2$为土壤内溶于$K_2CO_3$溶液并受溴化物水解的有机磷,$X_3$为土壤内溶于$K_2CO_3$溶液但不溶于溴化物水解的有机磷,
```{r echo=FALSE}
p<-data.frame(
  x1 <- c(0.4,0.4,3.1,0.6,4.7,1.7,9.4,10.1,11.6,12.6,10.9,23.1,23.1,21.6,23.1,1.9,26.8,29.9), 
  x2 <- c(52,34,19,34,24,65,44,31,29,58,37,46,50,44,56,36,58,51), 
  x3 <- c(158,163,37,157,59,123,46,117,173,112,111,114,134,73,168,143,202,124), 
  y <- c(64,60,71,61,54,77,81,93,93,51,76,96,77,93,95,54,168,99)
)
colnames(p) <- c("x1","x2","x3","y")
```
#### (1)求出$Y$关于$X$的多元线性回归方程.
```{r}
plot(p)
lm.sol<-lm(y~x1+x2+x3,data=p)
summary(lm.sol)
```
所以,Y$关于$X$的多元线性回归方程为
$Y=`r (lm.sol$coefficients[1])`+`r (lm.sol$coefficients[2])`X_1+`r (lm.sol$coefficients[3])`X_2+`r (lm.sol$coefficients[3])`X_3$

#### (2)对方差做显著性检验.
回归方程显著，但$X_2$和$X_3$的回归系数不显著。

#### (3)对变量做逐步回归分析.
```{r}
lm.step <- step(lm.sol)
summary(lm.step)
```
可见,$x_3$的显著性水平不够理想
```{r}
drop1(lm.step)
```
尝试去除$x_3$
```{r}
lm.sol<-lm(y~x1,data=p)
summary(lm.sol)
```
可见,此时的常数项和相关系数皆显著.

